import { siteUrl, appPathname } from './paths';
import { usePathname } from './navigation';
import { useState, useRef, useEffect } from 'react';
import { ArrowUpRight, ArrowRight, ChevronDown, Menu, X, Phone, MapPin, BookOpen, CalendarDays, Monitor, ZoomIn, ChevronLeft, ChevronRight } from 'lucide-react';
import Home from './page';
import { servicePages, units } from './content';
import gallery from './gallery.json';
export const wa = (t: string) => `https://wa.me/551932728585?text=${encodeURIComponent(t)}`;
export function Header() { const [open, setOpen] = useState(false); const [services, setServices] = useState(false); const nav = useRef<HTMLElement>(null); useEffect(() => { const close = (e: MouseEvent) => { if (nav.current && !nav.current.contains(e.target as Node))
    setServices(false); }; document.addEventListener('click', close); return () => document.removeEventListener('click', close); }, []); const path = appPathname(); return <><a className="skip" href="#conteudo">Pular para o conteúdo</a><header className="header"><a href={siteUrl("/")} className="brand" aria-label="Advance, início"><b className="brand-mark">A</b><span>advance<small>AUTOESCOLA · CAMPINAS</small></span></a><nav ref={nav} className={open ? 'nav open' : 'nav'} aria-label="Menu principal" onKeyDown={e => { if (e.key === 'Escape') {
    setServices(false);
    setOpen(false);
} }}><a href={siteUrl("/quem-somos/")} aria-current={path === '/quem-somos/' ? 'page' : undefined}>A Advance</a><div className="nav-service"><button aria-expanded={services} aria-controls="service-menu" onClick={() => setServices(!services)}>Serviços <ChevronDown size={15}/></button>{services && <div className="service-menu" id="service-menu">{servicePages.map(s => <a key={s.slug} href={siteUrl('/' + s.slug + '/')}>{s.title}<ArrowUpRight size={15}/></a>)}</div>}</div>{[['Alunos', 'alunos'], ['Fotos', 'fotos'], ['Avalie-nos', 'avalie-nos'], ['Contato', 'contato']].map(([title, slug]) => <a href={siteUrl('/' + slug + '/')} key={slug} aria-current={path === `/${slug}/` ? 'page' : undefined}>{title}</a>)}</nav><a className="header-cta" href={siteUrl(wa('Olá! Quero conhecer os cursos da Advance.'))} target="_blank" rel="noreferrer">Vamos conversar <ArrowUpRight size={18}/></a><button className="menu-toggle" aria-label={open ? 'Fechar menu' : 'Abrir menu'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></header></>; }
export function Footer() { return <footer className="site-footer"><div className="footer-grid"><div><a href={siteUrl("/")} className="brand">advance ↗</a><p>Desde 1994, formando<br />novos caminhos em Campinas.</p><div className="social-links"><a href="https://www.instagram.com/autoescolaadvance/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.facebook.com/AUTOESCOLAADVANCE/" target="_blank" rel="noreferrer">Facebook ↗</a></div></div><div><h3>Seu caminho</h3>{servicePages.map(s => <a href={siteUrl('/' + s.slug + '/')} key={s.slug}>{s.title}</a>)}</div><div><h3>A Advance</h3>{[['Quem somos', 'quem-somos'], ['Área do aluno', 'alunos'], ['Galeria de fotos', 'fotos'], ['Avalie-nos', 'avalie-nos'], ['Contato e unidades', 'contato']].map(([t, s]) => <a key={s} href={siteUrl('/' + s + '/')}>{t}</a>)}</div><div><h3>Vamos conversar</h3><a href="tel:+551932728585">João Jorge · (19) 3272-8585</a><a href="tel:+551932899499">Barão Geraldo · (19) 3289-9499</a><a href={siteUrl(wa('Olá! Gostaria de falar com a Advance.'))} target="_blank" rel="noreferrer">Atendimento pelo WhatsApp ↗</a></div></div><div className="footer-bottom"><span>Autoescola Advance · Campinas, SP</span><span>Proposta de redesign · Protótipo</span><a href="https://autoescolaadvance.com.br/" target="_blank" rel="noreferrer">Site atual ↗</a></div></footer>; }
function Intro({ title, label, headline, accent, intro }: {
    title: string;
    label: string;
    headline: string;
    accent: string;
    intro: string;
}) { return <section className="inner-intro"><nav className="breadcrumbs" aria-label="Localização"><a href={siteUrl("/")}>Início</a><span>/</span><span aria-current="page">{title}</span></nav><span className="eyebrow">{label}</span><h1>{headline}<br /><em>{accent}</em></h1><p>{intro}</p></section>; }
function SmallCTA({ title = 'Vamos encontrar seu próximo passo?', text = 'Converse com a equipe da Advance e tire suas dúvidas.' }) { return <section className="small-cta"><div><span className="eyebrow">A GENTE VAI COM VOCÊ.</span><h2>{title}</h2><p>{text}</p></div><a className="button" href={siteUrl("/contato/")}>Falar com a Advance <ArrowUpRight /></a></section>; }
export function UnitCards() { return <div className="location-grid">{units.map(l => <article className="location" key={l.n}><div className="location-top"><span>UNIDADE {l.n}</span><MapPin size={20}/></div><h3>{l.name}</h3><p>{l.addr}<br />Campinas, SP</p><small>{l.type}</small><a href={siteUrl('tel:+' + l.tel)}><Phone size={16}/>{l.phone}</a><a target="_blank" rel="noreferrer" href={siteUrl(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(l.addr + ', Campinas SP')}`)}>Como chegar <ArrowUpRight size={20}/></a></article>)}</div>; }
function Service({ slug }: {
    slug: string;
}) { const s = servicePages.find(p => p.slug === slug)!; return <><Intro {...s}/><section className="service-overview"><div className="service-photo"><img src={siteUrl(s.image)} alt={s.alt}/><span>{s.title} · Advance</span></div><aside><span className="eyebrow">SEU CAMINHO, COM ORIENTAÇÃO.</span><h2>Conte com a gente<br />em cada etapa.</h2><p>Escolha uma unidade e converse sobre aulas, horários e condições para começar.</p><a href={siteUrl(wa(`Olá! Gostaria de saber mais sobre ${s.title}.`))} className="button yellow" target="_blank" rel="noreferrer">Solicitar orçamento <ArrowUpRight size={20}/></a><a className="text-link" href={siteUrl("/contato/#unidades")}>Conhecer as unidades <ArrowRight size={18}/></a></aside></section><section className="service-body"><div className="service-sidebar"><span className="eyebrow">CONHEÇA A FORMAÇÃO</span><h2>Informação para<br />decidir melhor.</h2><nav aria-label="Nesta página">{s.sections.map((p, i) => <a key={p.title} href={siteUrl('#etapa-' + i)}>{String(i + 1).padStart(2, '0')} — {p.title}</a>)}</nav></div><div className="service-articles">{s.sections.map((p, i) => <article id={'etapa-' + i} key={p.title}><span>{String(i + 1).padStart(2, '0')}</span><div><h2>{p.title}</h2><p>{p.text}</p></div></article>)}<p className="process-note">Consulte a equipe para confirmar oferta, etapas e condições atuais antes da matrícula.</p></div></section><section className="faq-section"><div><span className="eyebrow">ANTES DE COMEÇAR</span><h2>Suas dúvidas,<br /><em>um passo de cada vez.</em></h2></div><div>{s.faq.map(([q, a]) => <details key={q}><summary>{q}<ChevronDown size={20}/></summary><p>{a}</p></details>)}</div></section><section className="related-services"><span className="eyebrow">OUTROS CAMINHOS</span>{servicePages.filter(p => p.slug !== slug).map(p => <a href={siteUrl('/' + p.slug + '/')} key={p.slug}>{p.title}<ArrowUpRight /></a>)}</section><SmallCTA /></>; }
function About() { return <><Intro title="Quem somos" label="ADVANCE · DESDE 1994" headline="Gente que ensina." accent="Caminhos que mudam." intro="Uma história construída em Campinas, ao lado de quem dá os primeiros passos ao volante."/><section className="about-story"><img src={siteUrl("/unidade.jpg")} alt="Fachada da Autoescola Advance"/><div><span className="year">1994</span><h2>Experiência que<br /><em>acompanha você.</em></h2><p>A Advance nasceu com o compromisso de preparar condutores conscientes e responsáveis. A formação reúne ensino, prática e apoio ao aluno.</p><p>Da primeira habilitação à ampliação de categoria, a equipe acompanha diferentes momentos da vida de quem dirige.</p><a className="text-link" href={siteUrl("/primeira-habilitacao/")}>Conheça a formação <ArrowUpRight size={20}/></a></div></section><section className="about-features"><article><span>01</span><h2>Aprender com apoio</h2><p>Profissionais dedicados ao ensino e à orientação nas aulas teóricas e práticas.</p></article><article><span>02</span><h2>Estrutura para treinar</h2><p>Simuladores, veículos de formação e circuito próprio para moto. A unidade João Jorge conta com circuito coberto.</p></article><article><span>03</span><h2>Perto de você</h2><p>Unidades na Vila Industrial e em Barão Geraldo, em Campinas.</p></article></section><section className="section"><span className="eyebrow">CONHEÇA NOSSA CASA</span><h2 className="subheading">Três endereços.<br /><em>O mesmo compromisso.</em></h2><UnitCards /><a className="text-link" href={siteUrl("/fotos/")}>Veja nossa galeria de fotos <ArrowUpRight /></a></section><SmallCTA /></>; }
function Gallery() { const [active, setActive] = useState(0); const dialog = useRef<HTMLDialogElement>(null); const lastButton = useRef<HTMLButtonElement | null>(null); const show = (i: number, b: HTMLButtonElement) => { lastButton.current = b; setActive(i); dialog.current?.showModal(); }; return <><Intro title="Fotos" label="POR DENTRO DA ADVANCE" headline="O lugar dos seus" accent="novos começos." intro="Conheça os espaços, os veículos e os registros da escola. Uma visita à Advance, antes da sua primeira aula."/><section className="photo-gallery"><div className="gallery-count"><span>GALERIA ADVANCE</span><span>{gallery.length} fotografias · clique para ampliar</span></div><div className="gallery-grid">{gallery.map((p, i) => <button key={p.src} onClick={e => show(i, e.currentTarget)} aria-label={`Ampliar foto ${i + 1}`}><img src={siteUrl(p.src)} alt={p.alt} loading={i > 3 ? 'lazy' : 'eager'}/><span>{String(i + 1).padStart(2, '0')} <ZoomIn size={19}/></span></button>)}</div></section><dialog className="lightbox" ref={dialog} onClose={() => lastButton.current?.focus()} onClick={e => { if (e.target === e.currentTarget)
    dialog.current?.close(); }} onKeyDown={e => { if (e.key === 'ArrowRight')
    setActive((active + 1) % gallery.length); if (e.key === 'ArrowLeft')
    setActive((active - 1 + gallery.length) % gallery.length); }} aria-label="Galeria ampliada"><button className="lightbox-close" aria-label="Fechar foto" onClick={() => dialog.current?.close()}><X /></button><img src={siteUrl(gallery[active].src)} alt={gallery[active].alt}/><div className="lightbox-controls"><button aria-label="Foto anterior" onClick={() => setActive((active - 1 + gallery.length) % gallery.length)}><ChevronLeft /></button><span aria-live="polite">{active + 1} / {gallery.length}</span><button aria-label="Próxima foto" onClick={() => setActive((active + 1) % gallery.length)}><ChevronRight /></button></div></dialog><SmallCTA title="Venha conhecer de perto."/></>; }
function Students() { const links = [{ title: 'Agendamento teórico', icon: CalendarDays, text: 'Consulte os serviços de habilitação e as orientações de agendamento do Detran-SP.', url: 'https://www.detran.sp.gov.br/wps/portal/portaldetran/cidadao/habilitacao/fichaservico/processoCNH/f53ffbdd-f740-4621-9983-3b8b491ca206/#' }, { title: 'Simulado Detran', icon: BookOpen, text: 'Acesse o simulado indicado no site da Advance e pratique seus conhecimentos.', url: 'https://www.detran.sp.gov.br/simulado' }, { title: 'Serviço ao cidadão', icon: Monitor, text: 'Acesse o portal e-CNHsp para os serviços relacionados à sua habilitação.', url: 'http://www.e-cnhsp.sp.gov.br/' }]; return <><Intro title="Alunos" label="SEU APOIO FORA DA SALA DE AULA" headline="Seu aprendizado" accent="continua aqui." intro="Os acessos úteis para acompanhar sua formação, estudar e encontrar orientação."/><section className="student-links">{links.map((l, i) => <a key={l.title} href={siteUrl(l.url)} target="_blank" rel="noreferrer"><l.icon size={34}/><span className="eyebrow">0{i + 1} — PORTAL EXTERNO</span><h2>{l.title}</h2><p>{l.text}</p><span className="text-link">Acessar serviço <ArrowUpRight size={22}/></span></a>)}</section><section className="student-help"><h2>Precisa de ajuda<br /><em>com suas aulas?</em></h2><div><p>Para horários, dúvidas sobre a formação ou apoio no acesso aos portais, fale com a sua unidade.</p><a className="text-link" href={siteUrl("/contato/")}>Encontrar minha unidade <ArrowUpRight /></a><a className="text-link" href={siteUrl("/avalie-nos/")}>Compartilhar minha experiência <ArrowUpRight /></a></div></section><SmallCTA /></>; }
function Contact() { const [preview, setPreview] = useState(''); return <><Intro title="Contato" label="ESTAMOS AQUI PARA AJUDAR" headline="Uma conversa." accent="Muitas possibilidades." intro="Conte o que você procura. Nossa equipe ajuda a encontrar o próximo passo da sua formação."/><section className="form-layout"><aside><span className="eyebrow">FALE COM A ADVANCE</span><h2>Qual é o seu<br /><em>próximo destino?</em></h2><p>Escolha seu assunto e prepare uma mensagem para a equipe.</p><a className="text-link" href="tel:+551932728585"><Phone size={18}/>(19) 3272-8585</a><a className="text-link" href={siteUrl(wa('Olá! Quero falar com a Advance.'))} target="_blank" rel="noreferrer">Conversar no WhatsApp <ArrowUpRight /></a></aside><form className="contact-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); setPreview(`Olá, meu nome é ${f.get('nome')}.\nAssunto: ${f.get('assunto')}\nE-mail: ${f.get('email')}\nTelefone: ${f.get('telefone') || 'Não informado'}\nUnidade: ${f.get('unidade')}\n\n${f.get('mensagem')}`); }}><div className="form-row"><label>Seu nome *<input name="nome" autoComplete="name" required maxLength={100}/></label><label>E-mail *<input name="email" type="email" autoComplete="email" required maxLength={150}/></label></div><div className="form-row"><label>Telefone<input name="telefone" type="tel" autoComplete="tel" maxLength={25}/></label><label>Assunto *<select name="assunto" required><option value="">Selecione</option>{servicePages.map(s => <option key={s.slug}>{s.title}</option>)}<option>Outras informações</option></select></label></div><label>Unidade de interesse<select name="unidade"><option>Ainda não escolhi</option>{units.map(u => <option key={u.n}>{u.name} — {u.addr}</option>)}</select></label><label>Como podemos ajudar? *<textarea name="mensagem" rows={5} required maxLength={2000}/></label><p className="form-note">A mensagem será preparada aqui. Você poderá revisá-la antes de abrir o WhatsApp e confirmar o envio.</p><button className="button yellow" type="submit">Preparar mensagem <ArrowRight size={20}/></button>{preview && <div className="form-preview" role="status"><h3>Confira sua mensagem</h3><p>{preview}</p><a className="button yellow" href={siteUrl(wa(preview))} target="_blank" rel="noreferrer">Continuar no WhatsApp <ArrowUpRight size={19}/></a><small>Nada foi enviado automaticamente.</small></div>}<a className="original-form" href="https://autoescolaadvance.com.br/contato/" target="_blank" rel="noreferrer">Prefere o formulário de e-mail? Acesse o site atual ↗</a></form></section><section id="unidades" className="section contact-units"><span className="eyebrow">ESCOLHA SUA UNIDADE</span><h2 className="subheading">A gente está<br /><em>perto de você.</em></h2><UnitCards /><p className="shared-phone">WhatsApp informado pelas unidades: <a href="https://wa.me/5519974202495" target="_blank" rel="noreferrer">(19) 97420-2495 ↗</a></p></section></>; }
function Rating({ name, title }: {
    name: string;
    title: string;
}) { return <fieldset className="rating"><legend>{title} *</legend><div>{Array.from({ length: 11 }, (_, i) => <label key={i}><input type="radio" required name={name} value={i}/><span>{i}</span></label>)}</div><small>0 = muito insatisfeito · 10 = muito satisfeito</small></fieldset>; }
function Reviews() { const [summary, setSummary] = useState<Record<string, FormDataEntryValue> | null>(null); return <><Intro title="Avalie-nos" label="SUA EXPERIÊNCIA IMPORTA" headline="Sua voz faz parte" accent="do nosso caminho." intro="Compartilhe como foi aprender com a Advance. Sua opinião ajuda a cuidar de cada etapa do atendimento."/><section className="form-layout"><aside><span className="eyebrow">ESCUTA QUE APROXIMA</span><h2>Como foi<br /><em>sua experiência?</em></h2><p>Avalie o instrutor, o atendimento e conte o que podemos melhorar.</p><div className="prototype-note"><strong>Prévia do formulário</strong><p>Neste protótipo, você pode preencher e revisar sua avaliação. Para enviá-la à escola, use o formulário do site atual.</p></div><a className="text-link" href="https://autoescolaadvance.com.br/avalie-nos/" target="_blank" rel="noreferrer">Abrir formulário oficial <ArrowUpRight size={20}/></a></aside><form className="contact-form" onSubmit={e => { e.preventDefault(); setSummary(Object.fromEntries(new FormData(e.currentTarget))); }}><div className="form-row"><label>Nome do aluno *<input name="aluno" required autoComplete="name" maxLength={100}/></label><label>Nome do instrutor *<input name="instrutor" required maxLength={100}/></label></div><Rating name="notaInstrutor" title="Sua nota para o instrutor"/><label>Sobre as aulas e o instrutor *<textarea name="aulas" required rows={4} maxLength={2000}/></label><Rating name="notaAtendimento" title="Sua nota para o atendimento"/><label>Sobre o atendimento da escola *<textarea name="atendimento" required rows={4} maxLength={2000}/></label><label className="checkbox-label"><input type="checkbox" required/>Confirmo que fui ou sou aluno da Autoescola Advance.</label><button className="button yellow" type="submit">Revisar avaliação <ArrowRight size={20}/></button>{summary && <div className="form-preview" role="status"><h3>Avaliação revisada — ainda não enviada</h3><p>Aluno: {String(summary.aluno)}<br />Instrutor: {String(summary.instrutor)} · Nota {String(summary.notaInstrutor)}/10</p><p>{String(summary.aulas)}</p><p>Atendimento · Nota {String(summary.notaAtendimento)}/10<br />{String(summary.atendimento)}</p><a className="text-link" href="https://autoescolaadvance.com.br/avalie-nos/" target="_blank" rel="noreferrer">Enviar pelo formulário oficial <ArrowUpRight /></a><small>Preencha sua avaliação novamente no site atual para enviá-la. Nenhum dado desta prévia foi transmitido.</small></div>}</form></section></>; }
export default function Site() { const pathname = usePathname(); const slug = pathname.split('/').filter(Boolean)[0] || ''; const names: Record<string, string> = { 'quem-somos': 'Quem somos', alunos: 'Alunos', fotos: 'Fotos', 'avalie-nos': 'Avalie-nos', contato: 'Contato' }; useEffect(() => { document.title = (servicePages.find(s => s.slug === slug)?.title || names[slug] || 'Sua próxima direção') + ' — Advance'; }, [slug]); let page; if (!slug)
    return <Home />; if (servicePages.some(s => s.slug === slug))
    page = <Service slug={slug}/>;
else if (slug === 'quem-somos')
    page = <About />;
else if (slug === 'fotos')
    page = <Gallery />;
else if (slug === 'alunos')
    page = <Students />;
else if (slug === 'contato')
    page = <Contact />;
else if (slug === 'avalie-nos')
    page = <Reviews />;
else
    page = <Intro title="Página não encontrada" label="VAMOS VOLTAR AO CAMINHO" headline="Este caminho" accent="não foi encontrado." intro="Use o menu para encontrar a página desejada."/>; return <div key={pathname}><Header /><main id="conteudo" className="inner-page">{page}</main><Footer /></div>; }
